export {default as Login} from './Login/Login '
export { default as Home} from './Reception/Home/Home'
export {default as AllDoctors} from './Reception/AllDoctors/AllDoctors'
export {default as Redirect} from './Redirect/Redirect'
export {default as DoctorReservedAppoinments} from './Reception/DoctorReservedAppoinments/DoctorReservedAppoinments'
export {default as EditAppoinments} from './Reception/EditAppoinments/EditAppoinments'
export{default as Devices} from './Reception/Devices/Devices'
export {default as DevicesReservedAppointments} from './Reception/DevicesReservedAppointments/DevicesReservedAppointments'
export {default as Patients} from './Reception/Patients/Patients'
export {default as PatientAppointments} from './Reception/PatientAppointments/PatientAppointments'
export {default as EditDeviceAppointments} from './Reception/EditDeviceAppointments/EditDeviceAppointments'
export{default as DoctorsAppManager} from './AppManager/DoctorsAppManager/DoctorsAppManager'
export{default as AddDoctor} from  './AppManager/AddDoctor/AddDoctor'
export{default as AddTherapist}from'./AppManager/AddTherapist/AddTherapist'
export{default as DeviceAppManager} from './AppManager/DeviceAppManager/DeviceAppManager'
export{default as AddDevice} from './AppManager/AddDevice/AddDevice'
export{default as Offers} from './AppManager/Offers/Offers'
export{default as EditDoctor} from './AppManager/EditDoctor/EditDoctor'
export{default as EditTherapist} from './AppManager/EditTherapist/EditTherapist'
export{default as EditDevice} from './AppManager/EditDevice/EditDevice'
export{default as EditPatient} from './Reception/EditPatient/EditPatient'
export{default as AddOffer} from './AppManager/AddOffer/AddOffer'
export {default as Statistics} from './Manager/Statistics/Statistics'